Hosts:
  - IP: "172.31.45.155"
    Port: 3000
  - IP: "172.31.34.13"
    Port: 3000
  - IP: "172.31.46.191"
    Port: 3000
  - IP: "172.31.40.156"
    Port: 3000
Username: ""
Password: ""
Namespace: "namespace"
SetName: "test"
AutoDiscardingKeyCapacity: 5000000
AutoDiscardingKeyRatio: .1
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 15
ColumnWidth: 12
ThreadYamlFilePath: "threads.yaml"
LuaFilePath: "lua/example.lua"
SizeOfTheDummyPartOfTheRecord: 1220
BatchSize: 10

