Hosts:
  - IP: "localhost"
    Port: 3000
Username: ""
Password: ""
Namespace: "test"
SetName: "test"
AutoDiscardingKeyCapacity: 5000000
AutoDiscardingKeyRatio: .1
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 25
ThreadYamlFilePath: "threads.yaml"
LuaFilePath: "lua/example.lua"
SizeOfTheDummyPartOfTheRecord: 1220
BatchSize: 10
