Hosts:
  - IP: "172.31.45.155"
    Port: 3000
  - IP: "172.31.34.13"
    Port: 3000
  - IP: "172.31.46.191"
    Port: 3000
  - IP: "172.31.40.156"
    Port: 3000
Namespace: "Barclays"
SetName: "test"
AutoDiscardingKeyCapacity: 5000000
AutoDiscardingKeyRatio: .1
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 15
ThreadYamlFilePath: "threads.yaml"
LuaFilePath: "lua/example.lua"
SizeOfTheDummyPartOfTheRecord: 1220
