aerospikeConfiguration:
  hosts:
    -
      ip: "localhost"
      port: 3000
  username: ""
  password: ""
  namespace: "test"
  set: "test"
  truncateSet: True
outputWindowConfiguration:
  printIntervalSec: 1
  numberOfLinesBeforeReprintingTheHeader: 25
  columnWidth: 11
testConfiguration:
  perseusId: 1
  recordSize: 1220
  readBatchSize: 50
  writeBatchSize: 50
  readHitRatio: 0.8
  stringIndex: False
  numericIndex: False
  geoSpatialIndex: False
  udfAggregation: False
  rangeQuery: False
  rangeQueryConfiguration:
    maxTimeRangeChance: 0.00001
    maxTimeRange: 1000
    normalTimeRange: 5
