Hosts:
  - IP: "localhost"
    Port: 3000
Namespace: "test"
SetName: "test"
AutoDiscardingKeyCapacity: 5000000
AutoDiscardingKeyRatio: .1
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 25
ThreadConfFilePath: "threads.yaml"
LuaFilePath: "lua2/example.lua"
