# AWS Detail
AWS_REGION="eu-west-1"

# Cluster Detail
VER="7.1.0.2"
CLUSTER_NAME="S71"
NAMESPACE="load_test"
CLUSTER_STORAGE_TYPE="HYBRID" #HYBRID OR MEMORY
CLUSTER_REPLICATION_FACTOR=2
CLUSTER_NUMBER_OF_NODES="3"
CLUSTER_INSTANCE_TYPE="i4i.4xlarge"
CLUSTER_INSTANCE_NUMBER_OF_NVMES="1"
CLUSTER_INSTANCE_NUMBER_OF_PARTITION_ON_EACH_NVME="4"

# GRAFANA Detail
GRAFANA_NAME=${CLUSTER_NAME}"_GRAFANA"
GRAFANA_INSTANCE_TYPE="t3.xlarge"

# Client Detail
CLIENT_NAME="Perseus_${CLUSTER_NAME}"
CLIENT_INSTANCE_TYPE="c7g.16xlarge"
CLIENT_NUMBER_OF_NODES=1

# setup backend
aerolab config backend -t aws -r ${AWS_REGION}
