# AWS Detail
AWS_REGION="eu-west-1"

# Aerospike Detail
VER="7.1.0.5"
NAMESPACE_NAME="Test"
NAMESPACE_DEFAULT_TTL="1H"
NAMESPACE_STORAGE_TYPE="HMA" #HMA OR MEMORY
NAMESPACE_REPLICATION_FACTOR=2

# Cluster Detail
CLUSTER_NAME="Aerospike"
CLUSTER_NUMBER_OF_NODES="3"
CLUSTER_INSTANCE_TYPE="i4i.4xlarge"
CLUSTER_INSTANCE_NUMBER_OF_NVMES="1"
CLUSTER_INSTANCE_NUMBER_OF_PARTITION_ON_EACH_NVME="4"
CLUSTER_OVERPROVISIONING_PERCENTAGE=20

# GRAFANA Detail
GRAFANA_NAME=${CLUSTER_NAME}"_GRAFANA"
GRAFANA_INSTANCE_TYPE="t3.xlarge"

# Client Detail
CLIENT_NAME="Perseus_${CLUSTER_NAME}"
CLIENT_INSTANCE_TYPE="c6a.32xlarge" #Choose instances with more cpus, more than 32 GB of RAM, and no NVMe. C6a family are good choices.
CLIENT_NUMBER_OF_NODES=1

# Testcases
STRING_INDEX=True
NUMERIC_INDEX=True
GEO_SPATIAL_INDEX=True
UDF_AFFREGATION=True
TRUNCATE_SET=False

# Workload Details
RECORD_SIZE=1000 #Bytes
BATCH_READ_SIZE=50
BATCH_WRITE_SIZE=50
READ_HIT_RATIO=0.8

# Perseus Detail
KEY_CACHE_CAPACITY=1000000000 #The instance must have enough RAM to keep the key cache in memory. Each entry is 16 Bytes. 1 billion entries need 16 GB of Ram
KEY_CACHE_SAVE_RATIO=1.0

# setup backend
aerolab config backend -t aws -r ${AWS_REGION}
