Hosts:
  - IP: "_IP_"
    Port: 3000
Username: ""
Password: ""
Namespace: "_NAMESPACE_"
SetName: "test"
AutoDiscardingKeyCapacity: 50000000
AutoDiscardingKeyRatio: .1
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 25
ColumnWidth: 12
ThreadYamlFilePath: "threads.yaml"
LuaFilePath: "lua/example.lua"
SizeOfTheDummyPartOfTheRecord: 1220
BatchSize: 10