aerospikeConfiguration:
  hosts:
    -
      ip: "_IP_"
      port: 3000
  username: ""
  password: ""
  namespace: "_NAMESPACE_NAME_"
  set: "test"
  truncateSet: _TRUNCATE_SET_
outputWindowConfiguration:
  printIntervalSec: 1
  numberOfLinesBeforeReprintingTheHeader: 25
  columnWidth: 11
testConfiguration:
  keyCaching:
    cacheCapacity: _KEY_CACHE_CAPACITY_
    discardRatio: _KEY_CACHE_SAVE_RATIO_
  recordSize: _RECORD_SIZE_
  readBatchSize: _BATCH_READ_SIZE_
  writeBatchSize: _BATCH_WRITE_SIZE_
  readHitRatio: _READ_HIT_RATIO_
  stringIndex: _STRING_INDEX_
  numericIndex: _NUMERIC_INDEX_
  geoSpatialIndex: _GEO_SPATIAL_INDEX_
  udfAggregation: _UDF_AFFREGATION_
  rangeQuery: _RANGE_QUERY_
  rangeQueryConfiguration:
    maxTimeRangeChance: _CHANCE_OF_MAX_
    maxTimeRange: _MAX_RANGE_
    normalTimeRange: _NORMAL_RANGE_