Hosts:
  - IP: "_IP_"
    Port: 3000
Username: ""
Password: ""
Namespace: "_NAMESPACE_"
SetName: "test"
AutoDiscardingKeyCapacity: 100000000
AutoDiscardingKeyRatio: .2
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 25
ColumnWidth: 15
ThreadYamlFilePath: "threads.yaml"
LuaFilePath: "lua/example.lua"
SizeOfTheDummyPartOfTheRecord: 1000
BatchSize: 30
ReadHitRatio: 1.0