Hosts:
  - IP: "_IP_"
    Port: 3000
Username: ""
Password: ""
Namespace: "_NAMESPACE_"
SetName: "test"
AutoDiscardingKeyCapacity: 50000000
AutoDiscardingKeyRatio: .2
PrintIntervalSec: 1
NumberOfLinesToReprintHeader: 25
ColumnWidth: 13
ThreadYamlFilePath: "threads.yaml"
LuaFilePath: "lua/example.lua"
SizeOfTheDummyPartOfTheRecord: 100
BatchSize: 30
ReadHitRatio: .50